language: node_js
os:
    - linux
    - windows
    - osx
node_js:
    - "stable"
    - "6.4.0"
    - "4.5.0"
    - "4.0.0"
sudo: false
before_script:
    - npm install -g jshint
script:
    - npm test
after_script:
    - jshint --config=.jshintrc .
after_success:
    - bash <(curl -s https://codecov.io/bash)
